spring.application.name=wattram-backend

# PostgreSQL Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/wattgram_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:iamSB@293}

server.port=${PORT:8080}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
app.jwt-secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt-expiration-milliseconds=604800000

# File Upload Settings
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
